[package]
name = "entab"
version = "0.1.0"
authors = ["Roderick <rbovee@gmail.com>"]
edition = "2018"

[dependencies]
# parsing
memchr = "2.3.3"
# compression
flate2 = "1.0.14"
bzip2 = "0.3.3"
xz2 = "0.1.6"
