[workspace]
members = [
  "entab",
  "entab-cli",
  "entab-js",
  "entab-py",
]

exclude = [
  "entab-r",
  "entab-benchmarks",
]

[profile.release]
lto = true
codegen-units = 1

[profile.bench]
lto = true
opt-level = 3
overflow-checks = false
codegen-units = 1
