[package]
name = "entab-py"
version = "0.1.0"
authors = ["Roderick <rbovee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
entab = { path = "../entab", default-features = false, features = ["std", "compression"] }
memmap = "0.7"
pyo3 = { version = "0.11.1", features =["extension-module"] }

[lib]
name = "entab"
crate-type = ["cdylib"]
# required-features = ["pyo3/extension-module"]
