[package]
name = "entab-cli"
version = "0.2.2"
authors = ["Roderick <rbovee@gmail.com>"]
edition = "2018"
description = "Record-format file reader CLI"
readme = "README.md"
repository = "https://github.com/bovee/entab"
license = "MIT"
categories = ["command-line-utilities", "parsing", "science"]

[dependencies]
clap = "3.0.0-beta"
entab = { path = "../entab", version = "0.2.2" }
memchr = "2.3"
memmap = { version = "0.7", optional = true }

[features]
default = ["mmap"]
mmap = ["memmap"]

[[bin]]
name = "entab"
path = "src/main.rs"
